import os
import xml.etree.ElementTree as ET

strings_en = {
    "save": "Save",
    "cancel": "Cancel",
    "delete": "Delete",
    "edit": "Edit",
    "change": "Change",
    "none": "None",
    "dismiss": "Dismiss",
    "snooze": "Snooze (%1$sm)",
    "start": "Start",
    "pause": "Pause",
    "back": "Back",
    "ok": "OK",
    "ringing_bell": "Ringing Bell",
    "toggle_completion": "Toggle completion",
    "study_planner": "Study Planner",
    "calendar": "Calendar",
    "settings": "Settings",
    "add_task": "Add Task",
    "edit_task": "Edit Task",
    "task_title": "Task Title",
    "date": "Date: %1$s",
    "start_time": "Start Time: %1$s",
    "end_time": "End Time: %1$s",
    "reminder_time": "Reminder: %1$s",
    "not_set": "Not set",
    "delete_task": "Delete Task",
    "no_tasks_month": "No tasks scheduled for this month.",
    "add_study_plan": "Add Study Plan",
    "edit_study_plan": "Edit Study Plan",
    "subject": "Subject",
    "chapter_topic": "Chapter / Topic",
    "target_duration": "Target Duration (mins)",
    "alarm_1": "Alarm 1: %1$s",
    "alarm_2": "Alarm 2: %1$s",
    "delete_plan": "Delete Plan",
    "edit_plan": "Edit Plan",
    "start_study": "Start Study",
    "time_study": "Time: %1$s",
    "target_study": "Target: %1$sm",
    "no_plans_month": "No study plans scheduled for this month.",
    "in_progress": "In Progress",
    "time_to_study": "Time to study!",
    "repeat_schedule": "Repeat Schedule",
    "repeat_mode": "Repeat: %1$s",
    "repeat_once": "Repeat: Once",
    "daily": "Daily",
    "weekdays": "Weekdays",
    "weekends": "Weekends",
    "custom": "Custom",
    "select_days": "Select Days:",
    "skip_next": "Skip Next Occurrence",
    "next_skipped": "(Next Skipped)",
    "day_s": "S",
    "day_m": "M",
    "day_t": "T",
    "day_w": "W",
    "day_th": "T",
    "day_f": "F",
    "day_sa": "S",
    "language": "Language",
    "snooze_duration": "Snooze Duration",
    "premium_active": "Premium Active",
    "upgrade_to_premium": "Upgrade to Premium",
    "about": "About",
    "access_all_features": "You have access to all features.",
    "study_planner_version": "Study Planner Version 1.0",
    "focus_better": "Focus better and achieve your study goals.",
    "study_timer": "Study Timer",
    "stop_and_save": "Stop & Save",
    "focus_lock": "Focus Lock",
    "focus_lock_setup": "Focus Lock Setup",
    "cancel_focus_session": "Cancel Focus Session",
    "focus_lock_help": "Focus Lock helps you avoid distracting apps while studying.",
    "grant_usage_access": "Grant Usage Access Permission",
    "i_agree_start": "I Agree, Start",
    "focus_lock_warning": "Please choose the apps carefully. Once Focus Lock starts, the selected apps will remain blocked until the selected session ends. If you select an app by mistake, you may not be able to use it until the session finishes.",
    "start_focus_lock_min": "Start Focus Lock (Min 1 Hour)",
    "start_focus_lock_prompt": "Start Focus Lock?"
}

strings_hi = {
    "save": "सहेजें",
    "cancel": "रद्द करें",
    "delete": "हटाएं",
    "edit": "संपादित करें",
    "change": "बदलें",
    "none": "कोई नहीं",
    "dismiss": "खारिज करें",
    "snooze": "स्नूज़ (%1$sm)",
    "start": "शुरू करें",
    "pause": "रोकें",
    "back": "वापस",
    "ok": "ठीक है",
    "ringing_bell": "घंटी बज रही है",
    "toggle_completion": "पूरा होना टॉगल करें",
    "study_planner": "अध्ययन योजनाकार",
    "calendar": "कैलेंडर",
    "settings": "सेटिंग्स",
    "add_task": "कार्य जोड़ें",
    "edit_task": "कार्य संपादित करें",
    "task_title": "कार्य का शीर्षक",
    "date": "दिनांक: %1$s",
    "start_time": "प्रारंभ समय: %1$s",
    "end_time": "समाप्ति समय: %1$s",
    "reminder_time": "रिमाइंडर: %1$s",
    "not_set": "सेट नहीं है",
    "delete_task": "कार्य हटाएं",
    "no_tasks_month": "इस महीने के लिए कोई कार्य निर्धारित नहीं है।",
    "add_study_plan": "अध्ययन योजना जोड़ें",
    "edit_study_plan": "अध्ययन योजना संपादित करें",
    "subject": "विषय",
    "chapter_topic": "अध्याय / विषय",
    "target_duration": "लक्ष्य अवधि (मिनट)",
    "alarm_1": "अलार्म 1: %1$s",
    "alarm_2": "अलार्म 2: %1$s",
    "delete_plan": "योजना हटाएं",
    "edit_plan": "योजना संपादित करें",
    "start_study": "अध्ययन शुरू करें",
    "time_study": "समय: %1$s",
    "target_study": "लक्ष्य: %1$sm",
    "no_plans_month": "इस महीने के लिए कोई अध्ययन योजना निर्धारित नहीं है।",
    "in_progress": "प्रगति पर",
    "time_to_study": "अध्ययन का समय!",
    "repeat_schedule": "दोहराने का कार्यक्रम",
    "repeat_mode": "दोहराएं: %1$s",
    "repeat_once": "दोहराएं: एक बार",
    "daily": "दैनिक",
    "weekdays": "सप्ताह के दिन",
    "weekends": "सप्ताहांत",
    "custom": "कस्टम",
    "select_days": "दिन चुनें:",
    "skip_next": "अगली घटना छोड़ें",
    "next_skipped": "(अगला छोड़ा गया)",
    "day_s": "र",
    "day_m": "सो",
    "day_t": "मं",
    "day_w": "बु",
    "day_th": "गु",
    "day_f": "शु",
    "day_sa": "श",
    "language": "भाषा",
    "snooze_duration": "स्नूज़ अवधि",
    "premium_active": "प्रीमियम सक्रिय",
    "upgrade_to_premium": "प्रीमियम में अपग्रेड करें",
    "about": "के बारे में",
    "access_all_features": "आपके पास सभी सुविधाओं तक पहुंच है।",
    "study_planner_version": "अध्ययन योजनाकार संस्करण 1.0",
    "focus_better": "बेहतर ध्यान केंद्रित करें और अपने अध्ययन के लक्ष्यों को प्राप्त करें।",
    "study_timer": "अध्ययन टाइमर",
    "stop_and_save": "रोकें और सहेजें",
    "focus_lock": "फोकस लॉक",
    "focus_lock_setup": "फोकस लॉक सेटअप",
    "cancel_focus_session": "फोकस सत्र रद्द करें",
    "focus_lock_help": "फोकस लॉक आपको अध्ययन करते समय ध्यान भटकाने वाले ऐप्स से बचने में मदद करता है।",
    "grant_usage_access": "उपयोग पहुंच अनुमति प्रदान करें",
    "i_agree_start": "मैं सहमत हूं, शुरू करें",
    "focus_lock_warning": "कृपया ऐप्स को सावधानी से चुनें। एक बार फोकस लॉक शुरू होने के बाद, चयनित ऐप्स चयनित सत्र समाप्त होने तक अवरुद्ध रहेंगे। यदि आप गलती से कोई ऐप चुनते हैं, तो सत्र समाप्त होने तक आप उसका उपयोग नहीं कर पाएंगे।",
    "start_focus_lock_min": "फोकस लॉक शुरू करें (न्यूनतम 1 घंटा)",
    "start_focus_lock_prompt": "फोकस लॉक शुरू करें?"
}

strings_fr = {
    "save": "Enregistrer",
    "cancel": "Annuler",
    "delete": "Supprimer",
    "edit": "Modifier",
    "change": "Changer",
    "none": "Aucun",
    "dismiss": "Rejeter",
    "snooze": "Répéter (%1$sm)",
    "start": "Démarrer",
    "pause": "Pause",
    "back": "Retour",
    "ok": "OK",
    "ringing_bell": "Cloche qui sonne",
    "toggle_completion": "Basculer l'achèvement",
    "study_planner": "Planificateur",
    "calendar": "Calendrier",
    "settings": "Paramètres",
    "add_task": "Ajouter une tâche",
    "edit_task": "Modifier la tâche",
    "task_title": "Titre de la tâche",
    "date": "Date : %1$s",
    "start_time": "Heure de début : %1$s",
    "end_time": "Heure de fin : %1$s",
    "reminder_time": "Rappel : %1$s",
    "not_set": "Non défini",
    "delete_task": "Supprimer la tâche",
    "no_tasks_month": "Aucune tâche prévue pour ce mois.",
    "add_study_plan": "Ajouter un plan d'étude",
    "edit_study_plan": "Modifier le plan d'étude",
    "subject": "Matière",
    "chapter_topic": "Chapitre / Sujet",
    "target_duration": "Durée cible (mins)",
    "alarm_1": "Alarme 1 : %1$s",
    "alarm_2": "Alarme 2 : %1$s",
    "delete_plan": "Supprimer le plan",
    "edit_plan": "Modifier le plan",
    "start_study": "Commencer l'étude",
    "time_study": "Heure : %1$s",
    "target_study": "Cible : %1$sm",
    "no_plans_month": "Aucun plan d'étude prévu pour ce mois.",
    "in_progress": "En cours",
    "time_to_study": "C'est l'heure d'étudier !",
    "repeat_schedule": "Programme de répétition",
    "repeat_mode": "Répéter : %1$s",
    "repeat_once": "Répéter : Une fois",
    "daily": "Tous les jours",
    "weekdays": "En semaine",
    "weekends": "Le week-end",
    "custom": "Personnalisé",
    "select_days": "Sélectionner les jours :",
    "skip_next": "Ignorer la prochaine occurrence",
    "next_skipped": "(Prochain ignoré)",
    "day_s": "D",
    "day_m": "L",
    "day_t": "M",
    "day_w": "M",
    "day_th": "J",
    "day_f": "V",
    "day_sa": "S",
    "language": "Langue",
    "snooze_duration": "Durée de répétition",
    "premium_active": "Premium Actif",
    "upgrade_to_premium": "Passer à Premium",
    "about": "À propos",
    "access_all_features": "Vous avez accès à toutes les fonctionnalités.",
    "study_planner_version": "Planificateur d'étude Version 1.0",
    "focus_better": "Concentrez-vous mieux et atteignez vos objectifs.",
    "study_timer": "Minuteur d'étude",
    "stop_and_save": "Arrêter et Enregistrer",
    "focus_lock": "Verrouillage de concentration",
    "focus_lock_setup": "Configuration du verrouillage",
    "cancel_focus_session": "Annuler la session",
    "focus_lock_help": "Le verrouillage vous aide à éviter les applications distrayantes.",
    "grant_usage_access": "Accorder l'autorisation d'accès",
    "i_agree_start": "J'accepte, Démarrer",
    "focus_lock_warning": "Veuillez choisir les applications avec soin. Une fois démarrées, elles seront bloquées jusqu'à la fin de la session.",
    "start_focus_lock_min": "Démarrer le verrouillage (Min 1 Heure)",
    "start_focus_lock_prompt": "Démarrer le verrouillage ?"
}

strings_it = {
    "save": "Salva",
    "cancel": "Annulla",
    "delete": "Elimina",
    "edit": "Modifica",
    "change": "Cambia",
    "none": "Nessuno",
    "dismiss": "Ignora",
    "snooze": "Posponi (%1$sm)",
    "start": "Inizia",
    "pause": "Pausa",
    "back": "Indietro",
    "ok": "OK",
    "ringing_bell": "Campanella che suona",
    "toggle_completion": "Attiva/Disattiva completamento",
    "study_planner": "Piano di Studi",
    "calendar": "Calendario",
    "settings": "Impostazioni",
    "add_task": "Aggiungi Attività",
    "edit_task": "Modifica Attività",
    "task_title": "Titolo Attività",
    "date": "Data: %1$s",
    "start_time": "Ora di Inizio: %1$s",
    "end_time": "Ora di Fine: %1$s",
    "reminder_time": "Promemoria: %1$s",
    "not_set": "Non impostato",
    "delete_task": "Elimina Attività",
    "no_tasks_month": "Nessuna attività programmata per questo mese.",
    "add_study_plan": "Aggiungi Piano di Studi",
    "edit_study_plan": "Modifica Piano di Studi",
    "subject": "Materia",
    "chapter_topic": "Capitolo / Argomento",
    "target_duration": "Durata Obiettivo (min)",
    "alarm_1": "Sveglia 1: %1$s",
    "alarm_2": "Sveglia 2: %1$s",
    "delete_plan": "Elimina Piano",
    "edit_plan": "Modifica Piano",
    "start_study": "Inizia a Studiare",
    "time_study": "Ora: %1$s",
    "target_study": "Obiettivo: %1$sm",
    "no_plans_month": "Nessun piano di studi programmato per questo mese.",
    "in_progress": "In Corso",
    "time_to_study": "È ora di studiare!",
    "repeat_schedule": "Programma di Ripetizione",
    "repeat_mode": "Ripeti: %1$s",
    "repeat_once": "Ripeti: Una Volta",
    "daily": "Giornaliero",
    "weekdays": "Giorni Feriali",
    "weekends": "Fine Settimana",
    "custom": "Personalizzato",
    "select_days": "Seleziona i giorni:",
    "skip_next": "Salta Prossima Occorrenza",
    "next_skipped": "(Prossimo Saltato)",
    "day_s": "D",
    "day_m": "L",
    "day_t": "M",
    "day_w": "M",
    "day_th": "G",
    "day_f": "V",
    "day_sa": "S",
    "language": "Lingua",
    "snooze_duration": "Durata Posponi",
    "premium_active": "Premium Attivo",
    "upgrade_to_premium": "Passa a Premium",
    "about": "Informazioni",
    "access_all_features": "Hai accesso a tutte le funzionalità.",
    "study_planner_version": "Study Planner Versione 1.0",
    "focus_better": "Concentrati meglio e raggiungi i tuoi obiettivi di studio.",
    "study_timer": "Timer di Studio",
    "stop_and_save": "Ferma e Salva",
    "focus_lock": "Blocco Concentrazione",
    "focus_lock_setup": "Configurazione Blocco",
    "cancel_focus_session": "Annulla Sessione",
    "focus_lock_help": "Il blocco ti aiuta a evitare app che distraggono mentre studi.",
    "grant_usage_access": "Concedi Autorizzazione di Accesso",
    "i_agree_start": "Accetto, Inizia",
    "focus_lock_warning": "Scegli attentamente le app. Una volta avviato, le app saranno bloccate fino alla fine della sessione.",
    "start_focus_lock_min": "Avvia Blocco (Min 1 Ora)",
    "start_focus_lock_prompt": "Avviare il Blocco Concentrazione?"
}

strings_es = {
    "save": "Guardar",
    "cancel": "Cancelar",
    "delete": "Eliminar",
    "edit": "Editar",
    "change": "Cambiar",
    "none": "Ninguno",
    "dismiss": "Descartar",
    "snooze": "Posponer (%1$sm)",
    "start": "Comenzar",
    "pause": "Pausar",
    "back": "Atrás",
    "ok": "Aceptar",
    "ringing_bell": "Campana sonando",
    "toggle_completion": "Alternar estado",
    "study_planner": "Planificador",
    "calendar": "Calendario",
    "settings": "Ajustes",
    "add_task": "Añadir Tarea",
    "edit_task": "Editar Tarea",
    "task_title": "Título de la Tarea",
    "date": "Fecha: %1$s",
    "start_time": "Hora de inicio: %1$s",
    "end_time": "Hora de fin: %1$s",
    "reminder_time": "Recordatorio: %1$s",
    "not_set": "No establecido",
    "delete_task": "Eliminar Tarea",
    "no_tasks_month": "No hay tareas programadas para este mes.",
    "add_study_plan": "Añadir Plan de Estudio",
    "edit_study_plan": "Editar Plan de Estudio",
    "subject": "Materia",
    "chapter_topic": "Capítulo / Tema",
    "target_duration": "Duración objetivo (mins)",
    "alarm_1": "Alarma 1: %1$s",
    "alarm_2": "Alarma 2: %1$s",
    "delete_plan": "Eliminar Plan",
    "edit_plan": "Editar Plan",
    "start_study": "Comenzar Estudio",
    "time_study": "Hora: %1$s",
    "target_study": "Objetivo: %1$sm",
    "no_plans_month": "No hay planes programados para este mes.",
    "in_progress": "En Curso",
    "time_to_study": "¡Hora de estudiar!",
    "repeat_schedule": "Programa de repetición",
    "repeat_mode": "Repetir: %1$s",
    "repeat_once": "Repetir: Una vez",
    "daily": "Diariamente",
    "weekdays": "Días laborables",
    "weekends": "Fines de semana",
    "custom": "Personalizado",
    "select_days": "Seleccionar días:",
    "skip_next": "Omitir próxima ocurrencia",
    "next_skipped": "(Próximo omitido)",
    "day_s": "D",
    "day_m": "L",
    "day_t": "M",
    "day_w": "X",
    "day_th": "J",
    "day_f": "V",
    "day_sa": "S",
    "language": "Idioma",
    "snooze_duration": "Duración de repetición",
    "premium_active": "Premium Activo",
    "upgrade_to_premium": "Mejorar a Premium",
    "about": "Acerca de",
    "access_all_features": "Tienes acceso a todas las funciones.",
    "study_planner_version": "Study Planner Versión 1.0",
    "focus_better": "Concéntrate mejor y alcanza tus metas.",
    "study_timer": "Temporizador de Estudio",
    "stop_and_save": "Detener y Guardar",
    "focus_lock": "Bloqueo de Enfoque",
    "focus_lock_setup": "Configuración de Bloqueo",
    "cancel_focus_session": "Cancelar Sesión",
    "focus_lock_help": "El bloqueo te ayuda a evitar distracciones mientras estudias.",
    "grant_usage_access": "Otorgar Permiso de Acceso",
    "i_agree_start": "Acepto, Comenzar",
    "focus_lock_warning": "Elige las aplicaciones con cuidado. Permanecerán bloqueadas hasta que finalice la sesión.",
    "start_focus_lock_min": "Comenzar Bloqueo (Mín 1 Hora)",
    "start_focus_lock_prompt": "¿Comenzar Bloqueo?"
}

strings_pt = {
    "save": "Salvar",
    "cancel": "Cancelar",
    "delete": "Excluir",
    "edit": "Editar",
    "change": "Alterar",
    "none": "Nenhum",
    "dismiss": "Ignorar",
    "snooze": "Soneca (%1$sm)",
    "start": "Iniciar",
    "pause": "Pausar",
    "back": "Voltar",
    "ok": "OK",
    "ringing_bell": "Sino tocando",
    "toggle_completion": "Alternar conclusão",
    "study_planner": "Planejador",
    "calendar": "Calendário",
    "settings": "Configurações",
    "add_task": "Adicionar Tarefa",
    "edit_task": "Editar Tarefa",
    "task_title": "Título da Tarefa",
    "date": "Data: %1$s",
    "start_time": "Hora de início: %1$s",
    "end_time": "Hora de término: %1$s",
    "reminder_time": "Lembrete: %1$s",
    "not_set": "Não definido",
    "delete_task": "Excluir Tarefa",
    "no_tasks_month": "Nenhuma tarefa programada para este mês.",
    "add_study_plan": "Adicionar Plano de Estudo",
    "edit_study_plan": "Editar Plano de Estudo",
    "subject": "Matéria",
    "chapter_topic": "Capítulo / Tópico",
    "target_duration": "Duração alvo (mins)",
    "alarm_1": "Alarme 1: %1$s",
    "alarm_2": "Alarme 2: %1$s",
    "delete_plan": "Excluir Plano",
    "edit_plan": "Editar Plano",
    "start_study": "Iniciar Estudo",
    "time_study": "Hora: %1$s",
    "target_study": "Alvo: %1$sm",
    "no_plans_month": "Nenhum plano de estudo programado para este mês.",
    "in_progress": "Em Andamento",
    "time_to_study": "Hora de estudar!",
    "repeat_schedule": "Cronograma de repetição",
    "repeat_mode": "Repetir: %1$s",
    "repeat_once": "Repetir: Uma vez",
    "daily": "Diariamente",
    "weekdays": "Dias de semana",
    "weekends": "Finais de semana",
    "custom": "Personalizado",
    "select_days": "Selecionar dias:",
    "skip_next": "Pular próxima ocorrência",
    "next_skipped": "(Próximo pulado)",
    "day_s": "D",
    "day_m": "S",
    "day_t": "T",
    "day_w": "Q",
    "day_th": "Q",
    "day_f": "S",
    "day_sa": "S",
    "language": "Idioma",
    "snooze_duration": "Duração da Soneca",
    "premium_active": "Premium Ativo",
    "upgrade_to_premium": "Atualizar para Premium",
    "about": "Sobre",
    "access_all_features": "Você tem acesso a todos os recursos.",
    "study_planner_version": "Study Planner Versão 1.0",
    "focus_better": "Concentre-se melhor e alcance seus objetivos.",
    "study_timer": "Cronômetro de Estudo",
    "stop_and_save": "Parar e Salvar",
    "focus_lock": "Bloqueio de Foco",
    "focus_lock_setup": "Configuração de Bloqueio",
    "cancel_focus_session": "Cancelar Sessão",
    "focus_lock_help": "O bloqueio ajuda a evitar aplicativos que distraem enquanto estuda.",
    "grant_usage_access": "Conceder Permissão de Acesso",
    "i_agree_start": "Concordo, Iniciar",
    "focus_lock_warning": "Escolha os aplicativos com cuidado. Eles permanecerão bloqueados até o final da sessão.",
    "start_focus_lock_min": "Iniciar Bloqueio (Mín 1 Hora)",
    "start_focus_lock_prompt": "Iniciar Bloqueio?"
}

def create_xml(strings_dict, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    root = ET.Element("resources")
    for key, value in strings_dict.items():
        node = ET.SubElement(root, "string", name=key)
        # Escape characters correctly if needed
        # We replace single quotes with \' 
        safe_value = value.replace("'", "\\'")
        node.text = safe_value
    
    tree = ET.ElementTree(root)
    tree.write(path, encoding="utf-8", xml_declaration=True)

create_xml(strings_en, "app/src/main/res/values/strings.xml")
create_xml(strings_hi, "app/src/main/res/values-hi/strings.xml")
create_xml(strings_fr, "app/src/main/res/values-fr/strings.xml")
create_xml(strings_it, "app/src/main/res/values-it/strings.xml")
create_xml(strings_es, "app/src/main/res/values-es/strings.xml")
create_xml(strings_pt, "app/src/main/res/values-pt/strings.xml")

print("Generated string files!")
